### ISSUE TITLE
Bug parameter VirusSeq

### ISSUE THREAD

**Issue by robertclerc** [rosericazondekon/virusSeqPipeline#1]
Hello,

I try to run VirusSeq but it no want to recognize parameters. All the Mosaik aligner tools are allowed to be executed as files.

INPUT : 

`/home/clerc/Projet/VirusSeq/Mosaik_bin/MosaikBuild ‐st illumina ‐q /home/clerc/Projet/VirusSeq/L526401A/L526401A_1.fq.gz ‐q2 /home/clerc/Projet/VirusSeq/L526401A/L526401A_2.fq.gz ‐out L526401A_Virus.bin`

OUTPUT : 

> ERROR: The input read file not specified. Please select either the -bd, -fr, -gd, -q, or -srf parameters.
> 
> ERROR: An output read filename or reference filename was not specified. Please select either the -out or -oa parameter.
> 
> ERROR: Unknown sequencing technology. Please choose between '454', 'helicos', 'illumina', 'sanger', or 'solid'.
> Description: converts external read formats to native MOSAIK formats.

**Comment by rosericazondekon** [comment]
Dear Sir,
Thank you for your interest in VirusSeqPipeline. Please, follow carefully and exactly the instructions in the README. I noticed a couple of discrepancies in your message:
1. This command line application is named VirusSeqPipeline (not VirusSeq). Although built on top of VirusSeq, it is quite different from the original "VirusSeq software". 
2. If you did use VirusSeqPipeline, Please organize your FASTQ files by sample. FASTQ files belonging to the same sample, must be in the same folder. For example, L526401A_1.fq.gz and L526401A_2.fq.gz ought to be in the same sample L526401A (just as you seemingly did). Next, the sample folders must all be placed in the "samples" folder within the `VirusSeq` parent folder.

It seems to me that you experienced those errors because the file organization described above was not followed. Please create a `samples` folder inside `VirusSeq` and place your sample folder `L526401A` inside the folder `samples`. Next, use your command line prompt to change directory to the "VirusSeq" folder on your computer. Here is the expected file organization of the `VirusSeq` folder before you run the pipeline:
```shell
.
├── AllowExec.txt
├── Mosaik_bin
├── Mosaik_JumpDb
├── runAll.sh
├── samples
│   └── L526401A
│       ├── L526401A_1.fq.gz
│       ├── L526401A_2.fq.gz
└── VirusSeq_Script
```
 To process your samples, execute the following command from your terminal:
`bash runAll.sh`

I hope this helps. Feel free to reach out to me again in case you experience further issues.
Thank you,

Roseric Azondekon, PhD

**Comment by robertclerc** [comment]
Thanks for the anwser.

I had install with the good organisation : 
![Capture du 2019-03-20 12-21-32](https://user-images.githubusercontent.com/22726268/54682136-635a5300-4b0e-11e9-8398-d9b34f74f24b.png)

but I have an other error, MosaikBuil can't open FASTQ file for performing integrity check :
![Capture du 2019-03-20 12-21-57](https://user-images.githubusercontent.com/22726268/54682252-afa59300-4b0e-11e9-9fcb-26257031c6b6.png)

**Comment by rosericazondekon** [comment]
Dear Sir,
Thank you for reaching out. You are seemingly runnning the pipeline from a cluster. I suggest you consult your system administrator to assist you in giving enough privileges to MosaikAligner to run correctly on your cluster. I highly suggest though, that you run it first on your local Ubuntu machine before transitioning to a cluster.
If you are using the pipeline from an external media NTFS drive, you should read and follow the instructions in `AllowExec.txt` in order to allow executable file to run on your external drive.
Your FASTQ files might also be corrupted. I recommend that you redownload them or try other FASTQ files for testing purposes.
Again, always feel free to reach out if this issue remains unsolved on your end.
Thank you for your interest in virusSeqPipeline,

Roseric

**Comment by robertclerc** [comment]
Ok thanks you it's work now.

**Comment by rosericazondekon** [comment]
Great! I am glad it works. Enjoy virusSeqPipeline and please, do not forget to cite the original virusSeq paper by [Chen and collaborators](https://academic.oup.com/bioinformatics/article/29/2/266/202055 "VirusSeq: software to identify viruses and their integration sites using next-generation sequencing of human cancer tissue"). Also, do not forget to cite us and report the virusSeqPipeline github repository too. Finally, share the word about our work and never hesitate to reach out should you have further questions, suggestions, or recommendations.
Thank you,

Roseric
